AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  VitalLens-AI-App - CloudFormation template to deploy a health prediction API using AWS Lambda, S3, and API Gateway.

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.9
    Architectures:
      - x86_64
    Handler: predict.lambda_handler

Resources:

  HealthModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vitallens-health-models  # ✅ Change this if already taken

  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VitalLensPredictFunction
      CodeUri: lambda/
      Description: Predict health status using input vitals
      Policies:
        - S3ReadPolicy:
            BucketName: vitallens-health-models
      Environment:
        Variables:
          MODEL_BUCKET: vitallens-health-models
          MODEL_KEY: health_model.pkl
      Events:
        Api:
          Type: Api
          Properties:
            Path: /predict
            Method: post

Outputs:
  PredictApiUrl:
    Description: "API Gateway endpoint for the predict Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict"
